---
  spring.config.activate.on-profile: local

  spring:
    # Datasource Configuration
    datasource:
      url: jdbc:mysql://localhost:3307/study0907
      username: root
      password: dnflwlq1
      driver-class-name: org.mysql.jdbc.Driver
      hikari:
        maximum-pool-size: 10
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          default_batch_fetch_size: 20